# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Edit_Vm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditVM(object):
    def setupUi(self, EditVM):
        EditVM.setObjectName("EditVM")
        EditVM.resize(550, 679)
        EditVM.setMinimumSize(QtCore.QSize(550, 679))
        EditVM.setMaximumSize(QtCore.QSize(550, 679))
        self.widget = QtWidgets.QWidget(EditVM)
        self.widget.setGeometry(QtCore.QRect(20, 11, 520, 649))
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.machineNameLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.machineNameLABEL.setFont(font)
        self.machineNameLABEL.setObjectName("machineNameLABEL")
        self.verticalLayout.addWidget(self.machineNameLABEL)
        self.machineNameLINEEDIT = QtWidgets.QLineEdit(self.widget)
        self.machineNameLINEEDIT.setObjectName("machineNameLINEEDIT")
        self.verticalLayout.addWidget(self.machineNameLINEEDIT)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.typeLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeLABEL.setFont(font)
        self.typeLABEL.setObjectName("typeLABEL")
        self.horizontalLayout.addWidget(self.typeLABEL)
        self.typeCOMBOBOX = QtWidgets.QComboBox(self.widget)
        self.typeCOMBOBOX.setObjectName("typeCOMBOBOX")
        self.typeCOMBOBOX.addItem("")
        self.typeCOMBOBOX.addItem("")
        self.horizontalLayout.addWidget(self.typeCOMBOBOX)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.createVmLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.createVmLABEL.setFont(font)
        self.createVmLABEL.setObjectName("createVmLABEL")
        self.horizontalLayout_2.addWidget(self.createVmLABEL)
        self.openExistingBUTON = QtWidgets.QPushButton(self.widget)
        self.openExistingBUTON.setObjectName("openExistingBUTON")
        self.horizontalLayout_2.addWidget(self.openExistingBUTON)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vmOsLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vmOsLABEL.setFont(font)
        self.vmOsLABEL.setObjectName("vmOsLABEL")
        self.verticalLayout_2.addWidget(self.vmOsLABEL)
        self.vmOsCOMBOBOX = QtWidgets.QComboBox(self.widget)
        self.vmOsCOMBOBOX.setObjectName("vmOsCOMBOBOX")
        self.vmOsCOMBOBOX.addItem("")
        self.vmOsCOMBOBOX.addItem("")
        self.vmOsCOMBOBOX.addItem("")
        self.verticalLayout_2.addWidget(self.vmOsCOMBOBOX)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.malwareLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.malwareLABEL.setFont(font)
        self.malwareLABEL.setObjectName("malwareLABEL")
        self.verticalLayout_4.addWidget(self.malwareLABEL)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.malwareLINEEDIT = QtWidgets.QLineEdit(self.widget)
        self.malwareLINEEDIT.setObjectName("malwareLINEEDIT")
        self.horizontalLayout_4.addWidget(self.malwareLINEEDIT)
        self.malwareBrowseBUTTON = QtWidgets.QPushButton(self.widget)
        self.malwareBrowseBUTTON.setObjectName("malwareBrowseBUTTON")
        self.horizontalLayout_4.addWidget(self.malwareBrowseBUTTON)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.metasploitLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.metasploitLABEL.setFont(font)
        self.metasploitLABEL.setObjectName("metasploitLABEL")
        self.verticalLayout_5.addWidget(self.metasploitLABEL)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.metasploitLINEEDIT = QtWidgets.QLineEdit(self.widget)
        self.metasploitLINEEDIT.setObjectName("metasploitLINEEDIT")
        self.horizontalLayout_5.addWidget(self.metasploitLINEEDIT)
        self.metasploitBrowseBUTTON = QtWidgets.QPushButton(self.widget)
        self.metasploitBrowseBUTTON.setObjectName("metasploitBrowseBUTTON")
        self.horizontalLayout_5.addWidget(self.metasploitBrowseBUTTON)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scriptLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scriptLABEL.setFont(font)
        self.scriptLABEL.setObjectName("scriptLABEL")
        self.verticalLayout_6.addWidget(self.scriptLABEL)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scriptLINEEDIT = QtWidgets.QLineEdit(self.widget)
        self.scriptLINEEDIT.setObjectName("scriptLINEEDIT")
        self.horizontalLayout_9.addWidget(self.scriptLINEEDIT)
        self.scriptBrowseBUTTON = QtWidgets.QPushButton(self.widget)
        self.scriptBrowseBUTTON.setObjectName("scriptBrowseBUTTON")
        self.horizontalLayout_9.addWidget(self.scriptBrowseBUTTON)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.softwareLABEL = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.softwareLABEL.setFont(font)
        self.softwareLABEL.setObjectName("softwareLABEL")
        self.verticalLayout_3.addWidget(self.softwareLABEL)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.softwareTREEWIDGET = QtWidgets.QTreeWidget(self.widget)
        self.softwareTREEWIDGET.setObjectName("softwareTREEWIDGET")
        item_0 = QtWidgets.QTreeWidgetItem(self.softwareTREEWIDGET)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.softwareTREEWIDGET)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.softwareTREEWIDGET)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.softwareTREEWIDGET.header().setVisible(False)
        self.horizontalLayout_8.addWidget(self.softwareTREEWIDGET)
        self.softwareAddBUTTON = QtWidgets.QPushButton(self.widget)
        self.softwareAddBUTTON.setObjectName("softwareAddBUTTON")
        self.horizontalLayout_8.addWidget(self.softwareAddBUTTON)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.discardBUTTON = QtWidgets.QPushButton(self.widget)
        self.discardBUTTON.setObjectName("discardBUTTON")
        self.horizontalLayout_6.addWidget(self.discardBUTTON)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.settingsBUTTON = QtWidgets.QPushButton(self.widget)
        self.settingsBUTTON.setObjectName("settingsBUTTON")
        self.horizontalLayout_6.addWidget(self.settingsBUTTON)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.saveBUTTON = QtWidgets.QPushButton(self.widget)
        self.saveBUTTON.setObjectName("saveBUTTON")
        self.horizontalLayout_6.addWidget(self.saveBUTTON)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)

        self.retranslateUi(EditVM)
        QtCore.QMetaObject.connectSlotsByName(EditVM)

    def retranslateUi(self, EditVM):
        _translate = QtCore.QCoreApplication.translate
        EditVM.setWindowTitle(_translate("EditVM", "Edit VM"))
        self.machineNameLABEL.setText(_translate("EditVM", "Machine Name:"))
        self.typeLABEL.setText(_translate("EditVM", "Type:"))
        self.typeCOMBOBOX.setItemText(0, _translate("EditVM", "POV Entity"))
        self.typeCOMBOBOX.setItemText(1, _translate("EditVM", "Victim Entity"))
        self.createVmLABEL.setText(_translate("EditVM", "Create From Existing VM:"))
        self.openExistingBUTON.setText(_translate("EditVM", "Open Existing"))
        self.vmOsLABEL.setText(_translate("EditVM", "VM OS:"))
        self.vmOsCOMBOBOX.setItemText(0, _translate("EditVM", "Kali Linux"))
        self.vmOsCOMBOBOX.setItemText(1, _translate("EditVM", "Ubuntu"))
        self.vmOsCOMBOBOX.setItemText(2, _translate("EditVM", "Windows"))
        self.malwareLABEL.setText(_translate("EditVM", "Malware/Binary:"))
        self.malwareBrowseBUTTON.setText(_translate("EditVM", "Browse"))
        self.metasploitLABEL.setText(_translate("EditVM", "MetaSploit Module:"))
        self.metasploitBrowseBUTTON.setText(_translate("EditVM", "Browse"))
        self.scriptLABEL.setText(_translate("EditVM", "Script:"))
        self.scriptBrowseBUTTON.setText(_translate("EditVM", "Browse"))
        self.softwareLABEL.setText(_translate("EditVM", "Software:"))
        __sortingEnabled = self.softwareTREEWIDGET.isSortingEnabled()
        self.softwareTREEWIDGET.setSortingEnabled(False)
        self.softwareTREEWIDGET.topLevelItem(0).setText(0, _translate("EditVM", "All"))
        self.softwareTREEWIDGET.topLevelItem(0).child(0).setText(0, _translate("EditVM", "example"))
        self.softwareTREEWIDGET.topLevelItem(1).setText(0, _translate("EditVM", "Linux Specific"))
        self.softwareTREEWIDGET.topLevelItem(1).child(0).setText(0, _translate("EditVM", "example"))
        self.softwareTREEWIDGET.topLevelItem(2).setText(0, _translate("EditVM", "Windows Specific"))
        self.softwareTREEWIDGET.topLevelItem(2).child(0).setText(0, _translate("EditVM", "example"))
        self.softwareTREEWIDGET.setSortingEnabled(__sortingEnabled)
        self.softwareAddBUTTON.setText(_translate("EditVM", "Add"))
        self.discardBUTTON.setText(_translate("EditVM", "Discard"))
        self.settingsBUTTON.setText(_translate("EditVM", "System Settings"))
        self.saveBUTTON.setText(_translate("EditVM", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditVM = QtWidgets.QWidget()
    ui = Ui_EditVM()
    ui.setupUi(EditVM)
    EditVM.show()
    sys.exit(app.exec_())

