# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetworkSetupAdvanced.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_NetworkSetupAdvanced(object):
    
#####Enables Network Adapter Buttons
    def enableNetworkAdapterButtons(self):
        #Adapter 1
        if self.enableNetworkAdapterCHECKBOX.isChecked():
            self.attachedToCOMBO.setEnabled(True)
            self.nameCombo.setEnabled(True)
            self.label.setEnabled(True)
            self.label_10.setEnabled(True)
            self.enableAdvancedSettingsCHECK.setEnabled(True)
        else:
            self.attachedToCOMBO.setEnabled(False)
            self.nameCombo.setEnabled(False)
            self.label.setEnabled(False)
            self.label_10.setEnabled(False)
            self.enableAdvancedSettingsCHECK.setEnabled(False)
        # Adapter 2
        if self.enableNetworkAdapterCHECKBOX_2.isChecked():
            self.attachedToCOMBO_3.setEnabled(True)
            self.nameCombo_3.setEnabled(True)
            self.label_22.setEnabled(True)
            self.label_25.setEnabled(True)
            self.enableAdvancedSettingsCHECK_2.setEnabled(True)
        else:
            self.attachedToCOMBO_3.setEnabled(False)
            self.nameCombo_3.setEnabled(False)
            self.label_22.setEnabled(False)
            self.label_25.setEnabled(False)
            self.enableAdvancedSettingsCHECK_2.setEnabled(False)
        # Adapter 3
        if self.enableNetworkAdapterCHECKBOX_3.isChecked():
            self.attachedToCOMBO_4.setEnabled(True)
            self.nameCombo_4.setEnabled(True)
            self.label_27.setEnabled(True)
            self.label_30.setEnabled(True)
            self.enableAdvancedSettingsCHECK_3.setEnabled(True)
        else:
            self.attachedToCOMBO_4.setEnabled(False)
            self.nameCombo_4.setEnabled(False)
            self.label_27.setEnabled(False)
            self.label_30.setEnabled(False)
            self.enableAdvancedSettingsCHECK_3.setEnabled(False)
        # Adapter 4
        if self.enableNetworkAdapterCHECKBOX_4.isChecked():
            self.attachedToCOMBO_5.setEnabled(True)
            self.nameCombo_5.setEnabled(True)
            self.label_32.setEnabled(True)
            self.label_35.setEnabled(True)
            self.enableAdvancedSettingsCHECK_4.setEnabled(True)
        else:
            self.attachedToCOMBO_5.setEnabled(False)
            self.nameCombo_5.setEnabled(False)
            self.label_32.setEnabled(False)
            self.label_35.setEnabled(False)
            self.enableAdvancedSettingsCHECK_4.setEnabled(False)

########enable the advanced settings options of each adapter
    def enableAdvancedSettings(self):
        #Adapter 1
        if self.enableAdvancedSettingsCHECK.isChecked():
            self.label_13.setEnabled(True)
            self.adapterTypeCOMBO.setEnabled(True)
            self.label_14.setEnabled(True)
            self.promiscuousCOMBO.setEnabled(True)
            self.macAddressLINEEDIT.setEnabled(True)
            self.label_15.setEnabled(True)
            self.cableConnectedCHECK.setEnabled(True)

        else:
            self.label_13.setEnabled(False)
            self.adapterTypeCOMBO.setEnabled(False)
            self.label_14.setEnabled(False)
            self.promiscuousCOMBO.setEnabled(False)
            self.macAddressLINEEDIT.setEnabled(False)
            self.label_15.setEnabled(False)
            self.cableConnectedCHECK.setEnabled(False)

        # Adapter 2
        if self.enableAdvancedSettingsCHECK_2.isChecked():
            self.label_21.setEnabled(True)
            self.adapterTypeCOMBO_3.setEnabled(True)
            self.label_23.setEnabled(True)
            self.promiscuousCOMBO_3.setEnabled(True)
            self.macAddressLINEEDIT_3.setEnabled(True)
            self.label_24.setEnabled(True)
            self.cableConnectedCHECK_2.setEnabled(True)
        else:
            self.label_21.setEnabled(False)
            self.adapterTypeCOMBO_3.setEnabled(False)
            self.label_23.setEnabled(False)
            self.promiscuousCOMBO_3.setEnabled(False)
            self.macAddressLINEEDIT_3.setEnabled(False)
            self.label_24.setEnabled(False)
            self.cableConnectedCHECK_2.setEnabled(False)
        # Adapter 3
        if self.enableAdvancedSettingsCHECK_3.isChecked():
            self.label_26.setEnabled(True)
            self.adapterTypeCOMBO_4.setEnabled(True)
            self.label_28.setEnabled(True)
            self.promiscuousCOMBO_4.setEnabled(True)
            self.macAddressLINEEDIT_4.setEnabled(True)
            self.label_29.setEnabled(True)
            self.cableConnectedCHECK_3.setEnabled(True)
        else:
            self.label_26.setEnabled(False)
            self.adapterTypeCOMBO_4.setEnabled(False)
            self.label_28.setEnabled(False)
            self.promiscuousCOMBO_4.setEnabled(False)
            self.macAddressLINEEDIT_4.setEnabled(False)
            self.label_29.setEnabled(False)
            self.cableConnectedCHECK_3.setEnabled(False)
        # Adapter 4
        if self.enableAdvancedSettingsCHECK_4.isChecked():
            self.label_31.setEnabled(True)
            self.adapterTypeCOMBO_5.setEnabled(True)
            self.label_33.setEnabled(True)
            self.promiscuousCOMBO_5.setEnabled(True)
            self.macAddressLINEEDIT_5.setEnabled(True)
            self.label_34.setEnabled(True)
            self.cableConnectedCHECK_4.setEnabled(True)
        else:
            self.label_31.setEnabled(False)
            self.adapterTypeCOMBO_5.setEnabled(False)
            self.label_33.setEnabled(False)
            self.promiscuousCOMBO_5.setEnabled(False)
            self.macAddressLINEEDIT_5.setEnabled(False)
            self.label_34.setEnabled(False)
            self.cableConnectedCHECK_4.setEnabled(False)

    def setupUi(self, Dialog):
            Dialog.setObjectName("Dialog")
            Dialog.setEnabled(True)
            Dialog.resize(873, 647)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
            Dialog.setSizePolicy(sizePolicy)
            Dialog.setMinimumSize(QtCore.QSize(873, 647))
            Dialog.setMaximumSize(QtCore.QSize(873, 647))
            self.layoutWidget = QtWidgets.QWidget(Dialog)
            self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 601))
            self.layoutWidget.setObjectName("layoutWidget")
            self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
            self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_2.setObjectName("verticalLayout_2")
            self.label_9 = QtWidgets.QLabel(self.layoutWidget)
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.label_9.setFont(font)
            self.label_9.setAlignment(QtCore.Qt.AlignCenter)
            self.label_9.setObjectName("label_9")
            self.verticalLayout_2.addWidget(self.label_9)
            self.vmLIST = QtWidgets.QListWidget(self.layoutWidget)
            self.vmLIST.setObjectName("vmLIST")
            item = QtWidgets.QListWidgetItem()
            self.vmLIST.addItem(item)
            item = QtWidgets.QListWidgetItem()
            self.vmLIST.addItem(item)
            item = QtWidgets.QListWidgetItem()
            self.vmLIST.addItem(item)
            self.verticalLayout_2.addWidget(self.vmLIST)
            self.addMachineBUTTON = QtWidgets.QPushButton(self.layoutWidget)
            self.addMachineBUTTON.setObjectName("addMachineBUTTON")
            self.verticalLayout_2.addWidget(self.addMachineBUTTON)
            self.layoutWidget1 = QtWidgets.QWidget(Dialog)
            self.layoutWidget1.setGeometry(QtCore.QRect(180, 10, 481, 601))
            self.layoutWidget1.setObjectName("layoutWidget1")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
            self.verticalLayout.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout.setObjectName("verticalLayout")
            self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.label_4.setFont(font)
            self.label_4.setAlignment(QtCore.Qt.AlignCenter)
            self.label_4.setObjectName("label_4")
            self.verticalLayout.addWidget(self.label_4)
            self.horizontalLayout = QtWidgets.QHBoxLayout()
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.saveSessionBUTTON = QtWidgets.QPushButton(self.layoutWidget1)
            self.saveSessionBUTTON.setObjectName("saveSessionBUTTON")
            self.horizontalLayout.addWidget(self.saveSessionBUTTON)
            self.testNetworkBUTTON = QtWidgets.QPushButton(self.layoutWidget1)
            self.testNetworkBUTTON.setObjectName("testNetworkBUTTON")
            self.horizontalLayout.addWidget(self.testNetworkBUTTON)
            self.verticalLayout.addLayout(self.horizontalLayout)
            self.adapterWIDGET = QtWidgets.QTabWidget(self.layoutWidget1)
            self.adapterWIDGET.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
            self.adapterWIDGET.setObjectName("adapterWIDGET")
            self.adapter1TAB = QtWidgets.QWidget()
            self.adapter1TAB.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
            self.adapter1TAB.setObjectName("adapter1TAB")
            self.enableNetworkAdapterCHECKBOX = QtWidgets.QCheckBox(self.adapter1TAB)
            self.enableNetworkAdapterCHECKBOX.setGeometry(QtCore.QRect(31, 22, 181, 17))
            self.enableNetworkAdapterCHECKBOX.setChecked(True)
            self.enableNetworkAdapterCHECKBOX.setObjectName("enableNetworkAdapterCHECKBOX")
            self.enableAdvancedSettingsCHECK = QtWidgets.QCheckBox(self.adapter1TAB)
            self.enableAdvancedSettingsCHECK.setGeometry(QtCore.QRect(31, 116, 171, 17))
            self.enableAdvancedSettingsCHECK.setObjectName("enableAdvancedSettingsCHECK")
            self.cableConnectedCHECK = QtWidgets.QCheckBox(self.adapter1TAB)
            self.cableConnectedCHECK.setEnabled(False)
            self.cableConnectedCHECK.setGeometry(QtCore.QRect(31, 244, 131, 17))
            self.cableConnectedCHECK.setObjectName("cableConnectedCHECK")
            self.layoutWidget2 = QtWidgets.QWidget(self.adapter1TAB)
            self.layoutWidget2.setGeometry(QtCore.QRect(31, 140, 344, 24))
            self.layoutWidget2.setObjectName("layoutWidget2")
            self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
            self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_6.setObjectName("horizontalLayout_6")
            self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
            self.label_13.setEnabled(False)
            self.label_13.setObjectName("label_13")
            self.horizontalLayout_6.addWidget(self.label_13)
            self.adapterTypeCOMBO = QtWidgets.QComboBox(self.layoutWidget2)
            self.adapterTypeCOMBO.setEnabled(False)
            self.adapterTypeCOMBO.setObjectName("adapterTypeCOMBO")
            self.adapterTypeCOMBO.addItem("")
            self.adapterTypeCOMBO.addItem("")
            self.adapterTypeCOMBO.addItem("")
            self.adapterTypeCOMBO.addItem("")
            self.adapterTypeCOMBO.addItem("")
            self.adapterTypeCOMBO.addItem("")
            self.horizontalLayout_6.addWidget(self.adapterTypeCOMBO)
            self.layoutWidget3 = QtWidgets.QWidget(self.adapter1TAB)
            self.layoutWidget3.setGeometry(QtCore.QRect(31, 46, 211, 24))
            self.layoutWidget3.setObjectName("layoutWidget3")
            self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
            self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_3.setObjectName("horizontalLayout_3")
            self.label = QtWidgets.QLabel(self.layoutWidget3)
            self.label.setObjectName("label")
            self.horizontalLayout_3.addWidget(self.label)
            self.attachedToCOMBO = QtWidgets.QComboBox(self.layoutWidget3)
            self.attachedToCOMBO.setObjectName("attachedToCOMBO")
            self.attachedToCOMBO.addItem("")
            self.attachedToCOMBO.addItem("")
            self.attachedToCOMBO.addItem("")
            self.attachedToCOMBO.addItem("")
            self.attachedToCOMBO.addItem("")
            self.attachedToCOMBO.addItem("")
            self.attachedToCOMBO.addItem("")
            self.horizontalLayout_3.addWidget(self.attachedToCOMBO)
            self.layoutWidget4 = QtWidgets.QWidget(self.adapter1TAB)
            self.layoutWidget4.setGeometry(QtCore.QRect(31, 209, 210, 26))
            self.layoutWidget4.setObjectName("layoutWidget4")
            self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
            self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_4.setObjectName("horizontalLayout_4")
            self.label_15 = QtWidgets.QLabel(self.layoutWidget4)
            self.label_15.setEnabled(False)
            self.label_15.setObjectName("label_15")
            self.horizontalLayout_4.addWidget(self.label_15)
            self.macAddressLINEEDIT = QtWidgets.QLineEdit(self.layoutWidget4)
            # self.macAddressLINEEDIT.setEnabled(False)
            self.macAddressLINEEDIT.setObjectName("macAddressLINEEDIT")
            self.horizontalLayout_4.addWidget(self.macAddressLINEEDIT)
            self.splitter = QtWidgets.QSplitter(self.adapter1TAB)
            self.splitter.setGeometry(QtCore.QRect(31, 81, 251, 20))
            self.splitter.setOrientation(QtCore.Qt.Horizontal)
            self.splitter.setObjectName("splitter")
            self.label_10 = QtWidgets.QLabel(self.splitter)
            self.label_10.setObjectName("label_10")
            self.nameCombo = QtWidgets.QComboBox(self.splitter)
            self.nameCombo.setObjectName("nameCombo")
            self.nameCombo.addItem("")
            self.nameCombo.addItem("")
            self.nameCombo.addItem("")
            self.layoutWidget5 = QtWidgets.QWidget(self.adapter1TAB)
            self.layoutWidget5.setGeometry(QtCore.QRect(31, 174, 210, 24))
            self.layoutWidget5.setObjectName("layoutWidget5")
            self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
            self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_5.setObjectName("horizontalLayout_5")
            self.label_14 = QtWidgets.QLabel(self.layoutWidget5)
            self.label_14.setEnabled(False)
            self.label_14.setObjectName("label_14")
            self.horizontalLayout_5.addWidget(self.label_14)
            self.promiscuousCOMBO = QtWidgets.QComboBox(self.layoutWidget5)
            self.promiscuousCOMBO.setEnabled(False)
            self.promiscuousCOMBO.setObjectName("promiscuousCOMBO")
            self.promiscuousCOMBO.addItem("")
            self.promiscuousCOMBO.addItem("")
            self.promiscuousCOMBO.addItem("")
            self.horizontalLayout_5.addWidget(self.promiscuousCOMBO)
            self.adapterWIDGET.addTab(self.adapter1TAB, "")
            self.adapter2TAB = QtWidgets.QWidget()
            self.adapter2TAB.setObjectName("adapter2TAB")
            self.layoutWidget6 = QtWidgets.QWidget(self.adapter2TAB)
            self.layoutWidget6.setGeometry(QtCore.QRect(30, 148, 344, 24))
            self.layoutWidget6.setObjectName("layoutWidget6")
            self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget6)
            self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_11.setObjectName("horizontalLayout_11")
            self.label_21 = QtWidgets.QLabel(self.layoutWidget6)
            self.label_21.setEnabled(False)
            self.label_21.setObjectName("label_21")
            self.horizontalLayout_11.addWidget(self.label_21)
            self.adapterTypeCOMBO_3 = QtWidgets.QComboBox(self.layoutWidget6)
            self.adapterTypeCOMBO_3.setEnabled(False)
            self.adapterTypeCOMBO_3.setObjectName("adapterTypeCOMBO_3")
            self.adapterTypeCOMBO_3.addItem("")
            self.adapterTypeCOMBO_3.addItem("")
            self.adapterTypeCOMBO_3.addItem("")
            self.adapterTypeCOMBO_3.addItem("")
            self.adapterTypeCOMBO_3.addItem("")
            self.adapterTypeCOMBO_3.addItem("")
            self.horizontalLayout_11.addWidget(self.adapterTypeCOMBO_3)
            self.enableNetworkAdapterCHECKBOX_2 = QtWidgets.QCheckBox(self.adapter2TAB)
            self.enableNetworkAdapterCHECKBOX_2.setGeometry(QtCore.QRect(30, 30, 191, 17))
            self.enableNetworkAdapterCHECKBOX_2.setObjectName("enableNetworkAdapterCHECKBOX_2")
            self.layoutWidget_2 = QtWidgets.QWidget(self.adapter2TAB)
            self.layoutWidget_2.setGeometry(QtCore.QRect(30, 54, 211, 24))
            self.layoutWidget_2.setObjectName("layoutWidget_2")
            self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
            self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_12.setObjectName("horizontalLayout_12")
            self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
            self.label_22.setEnabled(False)
            self.label_22.setObjectName("label_22")
            self.horizontalLayout_12.addWidget(self.label_22)
            self.attachedToCOMBO_3 = QtWidgets.QComboBox(self.layoutWidget_2)
            self.attachedToCOMBO_3.setEnabled(False)
            self.attachedToCOMBO_3.setObjectName("attachedToCOMBO_3")
            self.attachedToCOMBO_3.addItem("")
            self.attachedToCOMBO_3.addItem("")
            self.attachedToCOMBO_3.addItem("")
            self.attachedToCOMBO_3.addItem("")
            self.attachedToCOMBO_3.addItem("")
            self.attachedToCOMBO_3.addItem("")
            self.attachedToCOMBO_3.addItem("")
            self.horizontalLayout_12.addWidget(self.attachedToCOMBO_3)
            self.enableAdvancedSettingsCHECK_2 = QtWidgets.QCheckBox(self.adapter2TAB)
            self.enableAdvancedSettingsCHECK_2.setEnabled(False)
            self.enableAdvancedSettingsCHECK_2.setGeometry(QtCore.QRect(30, 124, 181, 17))
            self.enableAdvancedSettingsCHECK_2.setObjectName("enableAdvancedSettingsCHECK_2")
            self.layoutWidget_3 = QtWidgets.QWidget(self.adapter2TAB)
            self.layoutWidget_3.setGeometry(QtCore.QRect(30, 217, 210, 26))
            self.layoutWidget_3.setObjectName("layoutWidget_3")
            self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
            self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_13.setObjectName("horizontalLayout_13")
            self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
            self.label_23.setEnabled(False)
            self.label_23.setObjectName("label_23")
            self.horizontalLayout_13.addWidget(self.label_23)
            self.macAddressLINEEDIT_3 = QtWidgets.QLineEdit(self.layoutWidget_3)
            self.macAddressLINEEDIT_3.setEnabled(False)
            self.macAddressLINEEDIT_3.setObjectName("macAddressLINEEDIT_3")
            self.horizontalLayout_13.addWidget(self.macAddressLINEEDIT_3)
            self.cableConnectedCHECK_2 = QtWidgets.QCheckBox(self.adapter2TAB)
            self.cableConnectedCHECK_2.setEnabled(False)
            self.cableConnectedCHECK_2.setGeometry(QtCore.QRect(30, 252, 141, 17))
            self.cableConnectedCHECK_2.setObjectName("cableConnectedCHECK_2")
            self.layoutWidget_4 = QtWidgets.QWidget(self.adapter2TAB)
            self.layoutWidget_4.setGeometry(QtCore.QRect(30, 182, 210, 24))
            self.layoutWidget_4.setObjectName("layoutWidget_4")
            self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
            self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_14.setObjectName("horizontalLayout_14")
            self.label_24 = QtWidgets.QLabel(self.layoutWidget_4)
            self.label_24.setEnabled(False)
            self.label_24.setObjectName("label_24")
            self.horizontalLayout_14.addWidget(self.label_24)
            self.promiscuousCOMBO_3 = QtWidgets.QComboBox(self.layoutWidget_4)
            self.promiscuousCOMBO_3.setEnabled(False)
            self.promiscuousCOMBO_3.setObjectName("promiscuousCOMBO_3")
            self.promiscuousCOMBO_3.addItem("")
            self.promiscuousCOMBO_3.addItem("")
            self.promiscuousCOMBO_3.addItem("")
            self.horizontalLayout_14.addWidget(self.promiscuousCOMBO_3)
            self.splitter_2 = QtWidgets.QSplitter(self.adapter2TAB)
            self.splitter_2.setGeometry(QtCore.QRect(30, 89, 251, 20))
            self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
            self.splitter_2.setObjectName("splitter_2")
            self.label_25 = QtWidgets.QLabel(self.splitter_2)
            self.label_25.setEnabled(False)
            self.label_25.setObjectName("label_25")
            self.nameCombo_3 = QtWidgets.QComboBox(self.splitter_2)
            self.nameCombo_3.setEnabled(False)
            self.nameCombo_3.setObjectName("nameCombo_3")
            self.nameCombo_3.addItem("")
            self.nameCombo_3.addItem("")
            self.nameCombo_3.addItem("")
            self.adapterWIDGET.addTab(self.adapter2TAB, "")
            self.adapter3TAB = QtWidgets.QWidget()
            self.adapter3TAB.setObjectName("adapter3TAB")
            self.layoutWidget_5 = QtWidgets.QWidget(self.adapter3TAB)
            self.layoutWidget_5.setGeometry(QtCore.QRect(20, 138, 344, 24))
            self.layoutWidget_5.setObjectName("layoutWidget_5")
            self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
            self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_15.setObjectName("horizontalLayout_15")
            self.label_26 = QtWidgets.QLabel(self.layoutWidget_5)
            self.label_26.setEnabled(False)
            self.label_26.setObjectName("label_26")
            self.horizontalLayout_15.addWidget(self.label_26)
            self.adapterTypeCOMBO_4 = QtWidgets.QComboBox(self.layoutWidget_5)
            self.adapterTypeCOMBO_4.setEnabled(False)
            self.adapterTypeCOMBO_4.setObjectName("adapterTypeCOMBO_4")
            self.adapterTypeCOMBO_4.addItem("")
            self.adapterTypeCOMBO_4.addItem("")
            self.adapterTypeCOMBO_4.addItem("")
            self.adapterTypeCOMBO_4.addItem("")
            self.adapterTypeCOMBO_4.addItem("")
            self.adapterTypeCOMBO_4.addItem("")
            self.horizontalLayout_15.addWidget(self.adapterTypeCOMBO_4)
            self.enableNetworkAdapterCHECKBOX_3 = QtWidgets.QCheckBox(self.adapter3TAB)
            self.enableNetworkAdapterCHECKBOX_3.setGeometry(QtCore.QRect(20, 20, 191, 17))
            self.enableNetworkAdapterCHECKBOX_3.setObjectName("enableNetworkAdapterCHECKBOX_3")
            self.layoutWidget_6 = QtWidgets.QWidget(self.adapter3TAB)
            self.layoutWidget_6.setGeometry(QtCore.QRect(20, 44, 211, 24))
            self.layoutWidget_6.setObjectName("layoutWidget_6")
            self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
            self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_16.setObjectName("horizontalLayout_16")
            self.label_27 = QtWidgets.QLabel(self.layoutWidget_6)
            self.label_27.setEnabled(False)
            self.label_27.setObjectName("label_27")
            self.horizontalLayout_16.addWidget(self.label_27)
            self.attachedToCOMBO_4 = QtWidgets.QComboBox(self.layoutWidget_6)
            self.attachedToCOMBO_4.setEnabled(False)
            self.attachedToCOMBO_4.setObjectName("attachedToCOMBO_4")
            self.attachedToCOMBO_4.addItem("")
            self.attachedToCOMBO_4.addItem("")
            self.attachedToCOMBO_4.addItem("")
            self.attachedToCOMBO_4.addItem("")
            self.attachedToCOMBO_4.addItem("")
            self.attachedToCOMBO_4.addItem("")
            self.attachedToCOMBO_4.addItem("")
            self.horizontalLayout_16.addWidget(self.attachedToCOMBO_4)
            self.enableAdvancedSettingsCHECK_3 = QtWidgets.QCheckBox(self.adapter3TAB)
            self.enableAdvancedSettingsCHECK_3.setEnabled(False)
            self.enableAdvancedSettingsCHECK_3.setGeometry(QtCore.QRect(20, 114, 191, 17))
            self.enableAdvancedSettingsCHECK_3.setObjectName("enableAdvancedSettingsCHECK_3")
            self.layoutWidget_7 = QtWidgets.QWidget(self.adapter3TAB)
            self.layoutWidget_7.setGeometry(QtCore.QRect(20, 207, 210, 26))
            self.layoutWidget_7.setObjectName("layoutWidget_7")
            self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
            self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_17.setObjectName("horizontalLayout_17")
            self.label_28 = QtWidgets.QLabel(self.layoutWidget_7)
            self.label_28.setEnabled(False)
            self.label_28.setObjectName("label_28")
            self.horizontalLayout_17.addWidget(self.label_28)
            self.macAddressLINEEDIT_4 = QtWidgets.QLineEdit(self.layoutWidget_7)
            self.macAddressLINEEDIT_4.setEnabled(False)
            self.macAddressLINEEDIT_4.setObjectName("macAddressLINEEDIT_4")
            self.horizontalLayout_17.addWidget(self.macAddressLINEEDIT_4)
            self.cableConnectedCHECK_3 = QtWidgets.QCheckBox(self.adapter3TAB)
            self.cableConnectedCHECK_3.setEnabled(False)
            self.cableConnectedCHECK_3.setGeometry(QtCore.QRect(20, 242, 131, 17))
            self.cableConnectedCHECK_3.setObjectName("cableConnectedCHECK_3")
            self.layoutWidget_8 = QtWidgets.QWidget(self.adapter3TAB)
            self.layoutWidget_8.setGeometry(QtCore.QRect(20, 172, 210, 24))
            self.layoutWidget_8.setObjectName("layoutWidget_8")
            self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
            self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_18.setObjectName("horizontalLayout_18")
            self.label_29 = QtWidgets.QLabel(self.layoutWidget_8)
            self.label_29.setEnabled(False)
            self.label_29.setObjectName("label_29")
            self.horizontalLayout_18.addWidget(self.label_29)
            self.promiscuousCOMBO_4 = QtWidgets.QComboBox(self.layoutWidget_8)
            self.promiscuousCOMBO_4.setEnabled(False)
            self.promiscuousCOMBO_4.setObjectName("promiscuousCOMBO_4")
            self.promiscuousCOMBO_4.addItem("")
            self.promiscuousCOMBO_4.addItem("")
            self.promiscuousCOMBO_4.addItem("")
            self.horizontalLayout_18.addWidget(self.promiscuousCOMBO_4)
            self.splitter_3 = QtWidgets.QSplitter(self.adapter3TAB)
            self.splitter_3.setGeometry(QtCore.QRect(20, 79, 251, 20))
            self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
            self.splitter_3.setObjectName("splitter_3")
            self.label_30 = QtWidgets.QLabel(self.splitter_3)
            self.label_30.setEnabled(False)
            self.label_30.setObjectName("label_30")
            self.nameCombo_4 = QtWidgets.QComboBox(self.splitter_3)
            self.nameCombo_4.setEnabled(False)
            self.nameCombo_4.setObjectName("nameCombo_4")
            self.nameCombo_4.addItem("")
            self.nameCombo_4.addItem("")
            self.nameCombo_4.addItem("")
            self.adapterWIDGET.addTab(self.adapter3TAB, "")
            self.adapter4TAB = QtWidgets.QWidget()
            self.adapter4TAB.setObjectName("adapter4TAB")
            self.layoutWidget_9 = QtWidgets.QWidget(self.adapter4TAB)
            self.layoutWidget_9.setGeometry(QtCore.QRect(20, 128, 344, 24))
            self.layoutWidget_9.setObjectName("layoutWidget_9")
            self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
            self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_19.setObjectName("horizontalLayout_19")
            self.label_31 = QtWidgets.QLabel(self.layoutWidget_9)
            self.label_31.setEnabled(False)
            self.label_31.setObjectName("label_31")
            self.horizontalLayout_19.addWidget(self.label_31)
            self.adapterTypeCOMBO_5 = QtWidgets.QComboBox(self.layoutWidget_9)
            self.adapterTypeCOMBO_5.setEnabled(False)
            self.adapterTypeCOMBO_5.setObjectName("adapterTypeCOMBO_5")
            self.adapterTypeCOMBO_5.addItem("")
            self.adapterTypeCOMBO_5.addItem("")
            self.adapterTypeCOMBO_5.addItem("")
            self.adapterTypeCOMBO_5.addItem("")
            self.adapterTypeCOMBO_5.addItem("")
            self.adapterTypeCOMBO_5.addItem("")
            self.horizontalLayout_19.addWidget(self.adapterTypeCOMBO_5)
            self.enableNetworkAdapterCHECKBOX_4 = QtWidgets.QCheckBox(self.adapter4TAB)
            self.enableNetworkAdapterCHECKBOX_4.setGeometry(QtCore.QRect(20, 10, 211, 17))
            self.enableNetworkAdapterCHECKBOX_4.setObjectName("enableNetworkAdapterCHECKBOX_4")
            self.layoutWidget_10 = QtWidgets.QWidget(self.adapter4TAB)
            self.layoutWidget_10.setGeometry(QtCore.QRect(20, 34, 211, 24))
            self.layoutWidget_10.setObjectName("layoutWidget_10")
            self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
            self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_20.setObjectName("horizontalLayout_20")
            self.label_32 = QtWidgets.QLabel(self.layoutWidget_10)
            self.label_32.setEnabled(False)
            self.label_32.setObjectName("label_32")
            self.horizontalLayout_20.addWidget(self.label_32)
            self.attachedToCOMBO_5 = QtWidgets.QComboBox(self.layoutWidget_10)
            self.attachedToCOMBO_5.setEnabled(False)
            self.attachedToCOMBO_5.setObjectName("attachedToCOMBO_5")
            self.attachedToCOMBO_5.addItem("")
            self.attachedToCOMBO_5.addItem("")
            self.attachedToCOMBO_5.addItem("")
            self.attachedToCOMBO_5.addItem("")
            self.attachedToCOMBO_5.addItem("")
            self.attachedToCOMBO_5.addItem("")
            self.attachedToCOMBO_5.addItem("")
            self.horizontalLayout_20.addWidget(self.attachedToCOMBO_5)
            self.enableAdvancedSettingsCHECK_4 = QtWidgets.QCheckBox(self.adapter4TAB)
            self.enableAdvancedSettingsCHECK_4.setEnabled(False)
            self.enableAdvancedSettingsCHECK_4.setGeometry(QtCore.QRect(20, 104, 171, 17))
            self.enableAdvancedSettingsCHECK_4.setObjectName("enableAdvancedSettingsCHECK_4")
            self.layoutWidget_11 = QtWidgets.QWidget(self.adapter4TAB)
            self.layoutWidget_11.setGeometry(QtCore.QRect(20, 197, 210, 26))
            self.layoutWidget_11.setObjectName("layoutWidget_11")
            self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
            self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_21.setObjectName("horizontalLayout_21")
            self.label_33 = QtWidgets.QLabel(self.layoutWidget_11)
            self.label_33.setEnabled(False)
            self.label_33.setObjectName("label_33")
            self.horizontalLayout_21.addWidget(self.label_33)
            self.macAddressLINEEDIT_5 = QtWidgets.QLineEdit(self.layoutWidget_11)
            self.macAddressLINEEDIT_5.setEnabled(False)
            self.macAddressLINEEDIT_5.setObjectName("macAddressLINEEDIT_5")
            self.horizontalLayout_21.addWidget(self.macAddressLINEEDIT_5)
            self.cableConnectedCHECK_4 = QtWidgets.QCheckBox(self.adapter4TAB)
            self.cableConnectedCHECK_4.setEnabled(False)
            self.cableConnectedCHECK_4.setGeometry(QtCore.QRect(20, 232, 131, 17))
            self.cableConnectedCHECK_4.setObjectName("cableConnectedCHECK_4")
            self.layoutWidget_12 = QtWidgets.QWidget(self.adapter4TAB)
            self.layoutWidget_12.setGeometry(QtCore.QRect(20, 162, 210, 24))
            self.layoutWidget_12.setObjectName("layoutWidget_12")
            self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
            self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_22.setObjectName("horizontalLayout_22")
            self.label_34 = QtWidgets.QLabel(self.layoutWidget_12)
            self.label_34.setEnabled(False)
            self.label_34.setObjectName("label_34")
            self.horizontalLayout_22.addWidget(self.label_34)
            self.promiscuousCOMBO_5 = QtWidgets.QComboBox(self.layoutWidget_12)
            self.promiscuousCOMBO_5.setEnabled(False)
            self.promiscuousCOMBO_5.setObjectName("promiscuousCOMBO_5")
            self.promiscuousCOMBO_5.addItem("")
            self.promiscuousCOMBO_5.addItem("")
            self.promiscuousCOMBO_5.addItem("")
            self.horizontalLayout_22.addWidget(self.promiscuousCOMBO_5)
            self.splitter_4 = QtWidgets.QSplitter(self.adapter4TAB)
            self.splitter_4.setGeometry(QtCore.QRect(20, 69, 251, 20))
            self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
            self.splitter_4.setObjectName("splitter_4")
            self.label_35 = QtWidgets.QLabel(self.splitter_4)
            self.label_35.setEnabled(False)
            self.label_35.setObjectName("label_35")
            self.nameCombo_5 = QtWidgets.QComboBox(self.splitter_4)
            self.nameCombo_5.setEnabled(False)
            self.nameCombo_5.setObjectName("nameCombo_5")
            self.nameCombo_5.addItem("")
            self.nameCombo_5.addItem("")
            self.nameCombo_5.addItem("")
            self.adapterWIDGET.addTab(self.adapter4TAB, "")
            self.verticalLayout.addWidget(self.adapterWIDGET)
            self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_2.setObjectName("horizontalLayout_2")
            self.backBUTTON = QtWidgets.QPushButton(self.layoutWidget1)
            self.backBUTTON.setObjectName("backBUTTON")
            self.horizontalLayout_2.addWidget(self.backBUTTON)
            spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.horizontalLayout_2.addItem(spacerItem)
            self.runScenarioBUTTON = QtWidgets.QPushButton(self.layoutWidget1)
            self.runScenarioBUTTON.setObjectName("runScenarioBUTTON")
            self.horizontalLayout_2.addWidget(self.runScenarioBUTTON)
            self.verticalLayout.addLayout(self.horizontalLayout_2)
            self.vmnInfoLIST = QtWidgets.QListWidget(Dialog)
            self.vmnInfoLIST.setGeometry(QtCore.QRect(670, 30, 181, 197))
            self.vmnInfoLIST.setObjectName("vmnInfoLIST")
            item = QtWidgets.QListWidgetItem()
            self.vmnInfoLIST.addItem(item)
            item = QtWidgets.QListWidgetItem()
            self.vmnInfoLIST.addItem(item)
            item = QtWidgets.QListWidgetItem()
            self.vmnInfoLIST.addItem(item)
            item = QtWidgets.QListWidgetItem()
            self.vmnInfoLIST.addItem(item)
            item = QtWidgets.QListWidgetItem()
            self.vmnInfoLIST.addItem(item)
            self.apiCHECKBOX = QtWidgets.QCheckBox(Dialog)
            self.apiCHECKBOX.setGeometry(QtCore.QRect(671, 437, 101, 17))
            self.apiCHECKBOX.setObjectName("apiCHECKBOX")
            self.label_3 = QtWidgets.QLabel(Dialog)
            self.label_3.setGeometry(QtCore.QRect(672, 286, 71, 16))
            self.label_3.setObjectName("label_3")
            self.label_6 = QtWidgets.QLabel(Dialog)
            self.label_6.setGeometry(QtCore.QRect(672, 462, 101, 16))
            self.label_6.setObjectName("label_6")
            self.portLINEEDIT = QtWidgets.QLineEdit(Dialog)
            self.portLINEEDIT.setGeometry(QtCore.QRect(672, 306, 137, 24))
            self.portLINEEDIT.setObjectName("portLINEEDIT")
            self.stopConditionCOMBO = QtWidgets.QComboBox(Dialog)
            self.stopConditionCOMBO.setGeometry(QtCore.QRect(672, 533, 141, 20))
            self.stopConditionCOMBO.setObjectName("stopConditionCOMBO")
            self.stopConditionCOMBO.addItem("")
            self.label_5 = QtWidgets.QLabel(Dialog)
            self.label_5.setGeometry(QtCore.QRect(672, 339, 101, 16))
            self.label_5.setObjectName("label_5")
            self.timeoutCHECKBOX = QtWidgets.QCheckBox(Dialog)
            self.timeoutCHECKBOX.setGeometry(QtCore.QRect(672, 560, 111, 17))
            self.timeoutCHECKBOX.setObjectName("timeoutCHECKBOX")
            self.label_7 = QtWidgets.QLabel(Dialog)
            self.label_7.setGeometry(QtCore.QRect(672, 513, 111, 16))
            self.label_7.setObjectName("label_7")
            self.networkTrafficCHECKBOX = QtWidgets.QCheckBox(Dialog)
            self.networkTrafficCHECKBOX.setGeometry(QtCore.QRect(672, 388, 121, 17))
            self.networkTrafficCHECKBOX.setObjectName("networkTrafficCHECKBOX")
            self.systemLogsCHECKBOX = QtWidgets.QCheckBox(Dialog)
            self.systemLogsCHECKBOX.setGeometry(QtCore.QRect(672, 412, 111, 17))
            self.systemLogsCHECKBOX.setObjectName("systemLogsCHECKBOX")
            self.label_2 = QtWidgets.QLabel(Dialog)
            self.label_2.setGeometry(QtCore.QRect(672, 235, 81, 16))
            self.label_2.setObjectName("label_2")
            self.collectorCOMBO = QtWidgets.QComboBox(Dialog)
            self.collectorCOMBO.setGeometry(QtCore.QRect(672, 359, 81, 20))
            self.collectorCOMBO.setObjectName("collectorCOMBO")
            self.collectorCOMBO.addItem("")
            self.startConditionLINEEDIT = QtWidgets.QLineEdit(Dialog)
            self.startConditionLINEEDIT.setGeometry(QtCore.QRect(672, 482, 137, 24))
            self.startConditionLINEEDIT.setObjectName("startConditionLINEEDIT")
            self.ipLINEEDIT = QtWidgets.QLineEdit(Dialog)
            self.ipLINEEDIT.setGeometry(QtCore.QRect(672, 255, 137, 24))
            self.ipLINEEDIT.setObjectName("ipLINEEDIT")
            self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
            self.doubleSpinBox.setGeometry(QtCore.QRect(673, 585, 55, 24))
            self.doubleSpinBox.setObjectName("doubleSpinBox")
            self.label_8 = QtWidgets.QLabel(Dialog)
            self.label_8.setGeometry(QtCore.QRect(735, 585, 81, 16))
            self.label_8.setObjectName("label_8")

            self.retranslateUi(Dialog)
            self.adapterWIDGET.setCurrentIndex(0)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Advanced Network Setup", "Advanced Network Setup"))
            self.label_9.setText(_translate("Dialog", "Virtual Machines"))
            __sortingEnabled = self.vmLIST.isSortingEnabled()
            self.vmLIST.setSortingEnabled(False)
            item = self.vmLIST.item(0)
            item.setText(_translate("Dialog", "Machine 1"))
            item = self.vmLIST.item(1)
            item.setText(_translate("Dialog", "Machine 2"))
            item = self.vmLIST.item(2)
            item.setText(_translate("Dialog", "Machine 3"))
            self.vmLIST.setSortingEnabled(__sortingEnabled)
            self.addMachineBUTTON.setText(_translate("Dialog", "Add Machine"))
            self.label_4.setText(_translate("Dialog", "Scenario"))
            self.saveSessionBUTTON.setText(_translate("Dialog", "Save Session"))
            self.testNetworkBUTTON.setText(_translate("Dialog", "Test Network "))
            self.enableNetworkAdapterCHECKBOX.setText(_translate("Dialog", "Enable Network Adapter"))
            self.enableAdvancedSettingsCHECK.setText(_translate("Dialog", "Enable Advanced Settings"))
            self.cableConnectedCHECK.setText(_translate("Dialog", "Cable Connected"))
            self.label_13.setText(_translate("Dialog", "Adapter Type:"))
            self.adapterTypeCOMBO.setItemText(0, _translate("Dialog", "PCnet-PCI II (Am79C970A)"))
            self.adapterTypeCOMBO.setItemText(1, _translate("Dialog", "PCnet-FAST III (Am79C973)"))
            self.adapterTypeCOMBO.setItemText(2, _translate("Dialog", "Intel PRO/1000 MT Desktop (82540EM)"))
            self.adapterTypeCOMBO.setItemText(3, _translate("Dialog", "Intel PRO/1000 T Server (82543GC)"))
            self.adapterTypeCOMBO.setItemText(4, _translate("Dialog", "Intel PRO/1000 MT Server (82545EM)"))
            self.adapterTypeCOMBO.setItemText(5, _translate("Dialog", "Paravirtualized Network (virtio-net)"))
            self.label.setText(_translate("Dialog", "Attached to:"))
            self.attachedToCOMBO.setItemText(0, _translate("Dialog", "Not Attached"))
            self.attachedToCOMBO.setItemText(1, _translate("Dialog", "NAT"))
            self.attachedToCOMBO.setItemText(2, _translate("Dialog", "NAT Network"))
            self.attachedToCOMBO.setItemText(3, _translate("Dialog", "Bridged Adapter"))
            self.attachedToCOMBO.setItemText(4, _translate("Dialog", "Internal Network"))
            self.attachedToCOMBO.setItemText(5, _translate("Dialog", "Host-only Adapter"))
            self.attachedToCOMBO.setItemText(6, _translate("Dialog", "Generic Driver"))
            self.label_15.setText(_translate("Dialog", "MAC Address"))
            self.label_10.setText(_translate("Dialog", "Name:"))
            self.nameCombo.setItemText(0, _translate("Dialog", "Intel(R) Wireless-AC 9560 160MHz"))
            self.nameCombo.setItemText(1, _translate("Dialog", "VirtualBox Host-Only Ethernet Adapter"))
            self.nameCombo.setItemText(2, _translate("Dialog", "Killer E2400 Gigabit Ethernet Controller"))
            self.label_14.setText(_translate("Dialog", "Promiscuous Mode:"))
            self.promiscuousCOMBO.setItemText(0, _translate("Dialog", "Allow VMs"))
            self.promiscuousCOMBO.setItemText(1, _translate("Dialog", "Deny"))
            self.promiscuousCOMBO.setItemText(2, _translate("Dialog", "Allow All"))
            self.adapterWIDGET.setTabText(self.adapterWIDGET.indexOf(self.adapter1TAB),
                                          _translate("Dialog", "Adapter 1"))
            self.label_21.setText(_translate("Dialog", "Adapter Type:"))
            self.adapterTypeCOMBO_3.setItemText(0, _translate("Dialog", "PCnet-PCI II (Am79C970A)"))
            self.adapterTypeCOMBO_3.setItemText(1, _translate("Dialog", "PCnet-FAST III (Am79C973)"))
            self.adapterTypeCOMBO_3.setItemText(2, _translate("Dialog", "Intel PRO/1000 MT Desktop (82540EM)"))
            self.adapterTypeCOMBO_3.setItemText(3, _translate("Dialog", "Intel PRO/1000 T Server (82543GC)"))
            self.adapterTypeCOMBO_3.setItemText(4, _translate("Dialog", "Intel PRO/1000 MT Server (82545EM)"))
            self.adapterTypeCOMBO_3.setItemText(5, _translate("Dialog", "Paravirtualized Network (virtio-net)"))
            self.enableNetworkAdapterCHECKBOX_2.setText(_translate("Dialog", "Enable Network Adapter"))
            self.label_22.setText(_translate("Dialog", "Attached to:"))
            self.attachedToCOMBO_3.setItemText(0, _translate("Dialog", "Not Attached"))
            self.attachedToCOMBO_3.setItemText(1, _translate("Dialog", "NAT"))
            self.attachedToCOMBO_3.setItemText(2, _translate("Dialog", "NAT Network"))
            self.attachedToCOMBO_3.setItemText(3, _translate("Dialog", "Bridged Adapter"))
            self.attachedToCOMBO_3.setItemText(4, _translate("Dialog", "Internal Network"))
            self.attachedToCOMBO_3.setItemText(5, _translate("Dialog", "Host-only Adapter"))
            self.attachedToCOMBO_3.setItemText(6, _translate("Dialog", "Generic Driver"))
            self.enableAdvancedSettingsCHECK_2.setText(_translate("Dialog", "Enable Advanced Settings"))
            self.label_23.setText(_translate("Dialog", "MAC Address"))
            self.cableConnectedCHECK_2.setText(_translate("Dialog", "Cable Connected"))
            self.label_24.setText(_translate("Dialog", "Promiscuous Mode:"))
            self.promiscuousCOMBO_3.setItemText(0, _translate("Dialog", "Allow VMs"))
            self.promiscuousCOMBO_3.setItemText(1, _translate("Dialog", "Deny"))
            self.promiscuousCOMBO_3.setItemText(2, _translate("Dialog", "Allow All"))
            self.label_25.setText(_translate("Dialog", "Name:"))
            self.nameCombo_3.setItemText(0, _translate("Dialog", "Intel(R) Wireless-AC 9560 160MHz"))
            self.nameCombo_3.setItemText(1, _translate("Dialog", "VirtualBox Host-Only Ethernet Adapter"))
            self.nameCombo_3.setItemText(2, _translate("Dialog", "Killer E2400 Gigabit Ethernet Controller"))
            self.adapterWIDGET.setTabText(self.adapterWIDGET.indexOf(self.adapter2TAB),
                                          _translate("Dialog", "Adapter 2"))
            self.label_26.setText(_translate("Dialog", "Adapter Type:"))
            self.adapterTypeCOMBO_4.setItemText(0, _translate("Dialog", "PCnet-PCI II (Am79C970A)"))
            self.adapterTypeCOMBO_4.setItemText(1, _translate("Dialog", "PCnet-FAST III (Am79C973)"))
            self.adapterTypeCOMBO_4.setItemText(2, _translate("Dialog", "Intel PRO/1000 MT Desktop (82540EM)"))
            self.adapterTypeCOMBO_4.setItemText(3, _translate("Dialog", "Intel PRO/1000 T Server (82543GC)"))
            self.adapterTypeCOMBO_4.setItemText(4, _translate("Dialog", "Intel PRO/1000 MT Server (82545EM)"))
            self.adapterTypeCOMBO_4.setItemText(5, _translate("Dialog", "Paravirtualized Network (virtio-net)"))
            self.enableNetworkAdapterCHECKBOX_3.setText(_translate("Dialog", "Enable Network Adapter"))
            self.label_27.setText(_translate("Dialog", "Attached to:"))
            self.attachedToCOMBO_4.setItemText(0, _translate("Dialog", "Not Attached"))
            self.attachedToCOMBO_4.setItemText(1, _translate("Dialog", "NAT"))
            self.attachedToCOMBO_4.setItemText(2, _translate("Dialog", "NAT Network"))
            self.attachedToCOMBO_4.setItemText(3, _translate("Dialog", "Bridged Adapter"))
            self.attachedToCOMBO_4.setItemText(4, _translate("Dialog", "Internal Network"))
            self.attachedToCOMBO_4.setItemText(5, _translate("Dialog", "Host-only Adapter"))
            self.attachedToCOMBO_4.setItemText(6, _translate("Dialog", "Generic Driver"))
            self.enableAdvancedSettingsCHECK_3.setText(_translate("Dialog", "Enable Advanced Settings"))
            self.label_28.setText(_translate("Dialog", "MAC Address"))
            self.cableConnectedCHECK_3.setText(_translate("Dialog", "Cable Connected"))
            self.label_29.setText(_translate("Dialog", "Promiscuous Mode:"))
            self.promiscuousCOMBO_4.setItemText(0, _translate("Dialog", "Allow VMs"))
            self.promiscuousCOMBO_4.setItemText(1, _translate("Dialog", "Deny"))
            self.promiscuousCOMBO_4.setItemText(2, _translate("Dialog", "Allow All"))
            self.label_30.setText(_translate("Dialog", "Name:"))
            self.nameCombo_4.setItemText(0, _translate("Dialog", "Intel(R) Wireless-AC 9560 160MHz"))
            self.nameCombo_4.setItemText(1, _translate("Dialog", "VirtualBox Host-Only Ethernet Adapter"))
            self.nameCombo_4.setItemText(2, _translate("Dialog", "Killer E2400 Gigabit Ethernet Controller"))
            self.adapterWIDGET.setTabText(self.adapterWIDGET.indexOf(self.adapter3TAB),
                                          _translate("Dialog", "Adapter 3"))
            self.label_31.setText(_translate("Dialog", "Adapter Type:"))
            self.adapterTypeCOMBO_5.setItemText(0, _translate("Dialog", "PCnet-PCI II (Am79C970A)"))
            self.adapterTypeCOMBO_5.setItemText(1, _translate("Dialog", "PCnet-FAST III (Am79C973)"))
            self.adapterTypeCOMBO_5.setItemText(2, _translate("Dialog", "Intel PRO/1000 MT Desktop (82540EM)"))
            self.adapterTypeCOMBO_5.setItemText(3, _translate("Dialog", "Intel PRO/1000 T Server (82543GC)"))
            self.adapterTypeCOMBO_5.setItemText(4, _translate("Dialog", "Intel PRO/1000 MT Server (82545EM)"))
            self.adapterTypeCOMBO_5.setItemText(5, _translate("Dialog", "Paravirtualized Network (virtio-net)"))
            self.enableNetworkAdapterCHECKBOX_4.setText(_translate("Dialog", "Enable Network Adapter"))
            self.label_32.setText(_translate("Dialog", "Attached to:"))
            self.attachedToCOMBO_5.setItemText(0, _translate("Dialog", "Not Attached"))
            self.attachedToCOMBO_5.setItemText(1, _translate("Dialog", "NAT"))
            self.attachedToCOMBO_5.setItemText(2, _translate("Dialog", "NAT Network"))
            self.attachedToCOMBO_5.setItemText(3, _translate("Dialog", "Bridged Adapter"))
            self.attachedToCOMBO_5.setItemText(4, _translate("Dialog", "Internal Network"))
            self.attachedToCOMBO_5.setItemText(5, _translate("Dialog", "Host-only Adapter"))
            self.attachedToCOMBO_5.setItemText(6, _translate("Dialog", "Generic Driver"))
            self.enableAdvancedSettingsCHECK_4.setText(_translate("Dialog", "Enable Advanced Settings"))
            self.label_33.setText(_translate("Dialog", "MAC Address"))
            self.cableConnectedCHECK_4.setText(_translate("Dialog", "Cable Connected"))
            self.label_34.setText(_translate("Dialog", "Promiscuous Mode:"))
            self.promiscuousCOMBO_5.setItemText(0, _translate("Dialog", "Allow VMs"))
            self.promiscuousCOMBO_5.setItemText(1, _translate("Dialog", "Deny"))
            self.promiscuousCOMBO_5.setItemText(2, _translate("Dialog", "Allow All"))
            self.label_35.setText(_translate("Dialog", "Name:"))
            self.nameCombo_5.setItemText(0, _translate("Dialog", "Intel(R) Wireless-AC 9560 160MHz"))
            self.nameCombo_5.setItemText(1, _translate("Dialog", "VirtualBox Host-Only Ethernet Adapter"))
            self.nameCombo_5.setItemText(2, _translate("Dialog", "Killer E2400 Gigabit Ethernet Controller"))
            self.adapterWIDGET.setTabText(self.adapterWIDGET.indexOf(self.adapter4TAB),
                                          _translate("Dialog", "Adapter 4"))
            self.backBUTTON.setText(_translate("Dialog", "Back"))
            self.runScenarioBUTTON.setText(_translate("Dialog", "Run Scenario"))
            __sortingEnabled = self.vmnInfoLIST.isSortingEnabled()
            self.vmnInfoLIST.setSortingEnabled(False)
            item = self.vmnInfoLIST.item(0)
            item.setText(_translate("Dialog", "ICON "))
            item = self.vmnInfoLIST.item(1)
            item.setText(_translate("Dialog", "Name:"))
            item = self.vmnInfoLIST.item(2)
            item.setText(_translate("Dialog", "OS:"))
            item = self.vmnInfoLIST.item(3)
            item.setText(_translate("Dialog", "Vulnerability:"))
            item = self.vmnInfoLIST.item(4)
            item.setText(_translate("Dialog", "Collector:"))
            self.vmnInfoLIST.setSortingEnabled(__sortingEnabled)
            self.apiCHECKBOX.setText(_translate("Dialog", "API Calls"))
            self.label_3.setText(_translate("Dialog", "Port"))
            self.label_6.setText(_translate("Dialog", "Start Condition"))
            self.stopConditionCOMBO.setItemText(0, _translate("Dialog", "Duration/Condition met"))
            self.label_5.setText(_translate("Dialog", "Collector"))
            self.timeoutCHECKBOX.setText(_translate("Dialog", "Timeout"))
            self.label_7.setText(_translate("Dialog", "Stop Condition"))
            self.networkTrafficCHECKBOX.setText(_translate("Dialog", "Network Traffic"))
            self.systemLogsCHECKBOX.setText(_translate("Dialog", "System Logs"))
            self.label_2.setText(_translate("Dialog", "IP Adress"))
            self.collectorCOMBO.setItemText(0, _translate("Dialog", "ECELd"))
            self.label_8.setText(_translate("Dialog", "Seconds"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_NetworkSetupAdvanced()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
