# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetworkSetupAdvanced.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(873, 647)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(873, 647))
        Dialog.setMaximumSize(QtCore.QSize(873, 647))
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(12, 13, 171, 611))
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.networkElementsLIST = QtWidgets.QListWidget(self.widget)
        self.networkElementsLIST.setObjectName("networkElementsLIST")
        item = QtWidgets.QListWidgetItem()
        self.networkElementsLIST.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.networkElementsLIST.addItem(item)
        self.verticalLayout_9.addWidget(self.networkElementsLIST)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.vmLIST = QtWidgets.QListWidget(self.widget)
        self.vmLIST.setObjectName("vmLIST")
        item = QtWidgets.QListWidgetItem()
        self.vmLIST.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vmLIST.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vmLIST.addItem(item)
        self.verticalLayout.addWidget(self.vmLIST)
        self.addMachineBUTTON = QtWidgets.QPushButton(self.widget)
        self.addMachineBUTTON.setObjectName("addMachineBUTTON")
        self.verticalLayout.addWidget(self.addMachineBUTTON)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(670, 30, 181, 591))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.vmnInfoLIST = QtWidgets.QListWidget(self.splitter)
        self.vmnInfoLIST.setObjectName("vmnInfoLIST")
        item = QtWidgets.QListWidgetItem()
        self.vmnInfoLIST.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vmnInfoLIST.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vmnInfoLIST.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vmnInfoLIST.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.vmnInfoLIST.addItem(item)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.ipLINEEDIT = QtWidgets.QLineEdit(self.widget1)
        self.ipLINEEDIT.setObjectName("ipLINEEDIT")
        self.verticalLayout_3.addWidget(self.ipLINEEDIT)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.portLINEEDIT = QtWidgets.QLineEdit(self.widget1)
        self.portLINEEDIT.setObjectName("portLINEEDIT")
        self.verticalLayout_3.addWidget(self.portLINEEDIT)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.collectorCOMBO = QtWidgets.QComboBox(self.widget1)
        self.collectorCOMBO.setObjectName("collectorCOMBO")
        self.collectorCOMBO.addItem("")
        self.verticalLayout_5.addWidget(self.collectorCOMBO)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.networkTrafficCHECKBOX = QtWidgets.QCheckBox(self.widget1)
        self.networkTrafficCHECKBOX.setObjectName("networkTrafficCHECKBOX")
        self.verticalLayout_6.addWidget(self.networkTrafficCHECKBOX)
        self.systemLogsCHECKBOX = QtWidgets.QCheckBox(self.widget1)
        self.systemLogsCHECKBOX.setObjectName("systemLogsCHECKBOX")
        self.verticalLayout_6.addWidget(self.systemLogsCHECKBOX)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.apiCHECKBOX = QtWidgets.QCheckBox(self.widget1)
        self.apiCHECKBOX.setObjectName("apiCHECKBOX")
        self.verticalLayout_8.addWidget(self.apiCHECKBOX)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.startConditionLINEEDIT = QtWidgets.QLineEdit(self.widget1)
        self.startConditionLINEEDIT.setObjectName("startConditionLINEEDIT")
        self.verticalLayout_7.addWidget(self.startConditionLINEEDIT)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.stopConditionCOMBO = QtWidgets.QComboBox(self.widget1)
        self.stopConditionCOMBO.setObjectName("stopConditionCOMBO")
        self.stopConditionCOMBO.addItem("")
        self.verticalLayout_7.addWidget(self.stopConditionCOMBO)
        self.timeoutCHECKBOX = QtWidgets.QCheckBox(self.widget1)
        self.timeoutCHECKBOX.setObjectName("timeoutCHECKBOX")
        self.verticalLayout_7.addWidget(self.timeoutCHECKBOX)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(192, 12, 471, 611))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveSessionBUTTON = QtWidgets.QPushButton(self.widget2)
        self.saveSessionBUTTON.setObjectName("saveSessionBUTTON")
        self.horizontalLayout_3.addWidget(self.saveSessionBUTTON)
        self.testNetworkBUTTON = QtWidgets.QPushButton(self.widget2)
        self.testNetworkBUTTON.setObjectName("testNetworkBUTTON")
        self.horizontalLayout_3.addWidget(self.testNetworkBUTTON)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.graphicsView = QtWidgets.QGraphicsView(self.widget2)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backBUTTON = QtWidgets.QPushButton(self.widget2)
        self.backBUTTON.setObjectName("backBUTTON")
        self.horizontalLayout_2.addWidget(self.backBUTTON)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.runScenarioBUTTON = QtWidgets.QPushButton(self.widget2)
        self.runScenarioBUTTON.setObjectName("runScenarioBUTTON")
        self.horizontalLayout_2.addWidget(self.runScenarioBUTTON)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Advanced Network Setup", "Advanced Network Setup"))
        self.label.setText(_translate("Dialog", "Network Elements"))
        __sortingEnabled = self.networkElementsLIST.isSortingEnabled()
        self.networkElementsLIST.setSortingEnabled(False)
        item = self.networkElementsLIST.item(0)
        item.setText(_translate("Dialog", "Connection"))
        item = self.networkElementsLIST.item(1)
        item.setText(_translate("Dialog", "Server"))
        self.networkElementsLIST.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("Dialog", "Virtual Machines"))
        __sortingEnabled = self.vmLIST.isSortingEnabled()
        self.vmLIST.setSortingEnabled(False)
        item = self.vmLIST.item(0)
        item.setText(_translate("Dialog", "Machine 1"))
        item = self.vmLIST.item(1)
        item.setText(_translate("Dialog", "Machine 2"))
        item = self.vmLIST.item(2)
        item.setText(_translate("Dialog", "Machine 3"))
        self.vmLIST.setSortingEnabled(__sortingEnabled)
        self.addMachineBUTTON.setText(_translate("Dialog", "Add Machine"))
        __sortingEnabled = self.vmnInfoLIST.isSortingEnabled()
        self.vmnInfoLIST.setSortingEnabled(False)
        item = self.vmnInfoLIST.item(0)
        item.setText(_translate("Dialog", "ICON "))
        item = self.vmnInfoLIST.item(1)
        item.setText(_translate("Dialog", "Name:"))
        item = self.vmnInfoLIST.item(2)
        item.setText(_translate("Dialog", "OS:"))
        item = self.vmnInfoLIST.item(3)
        item.setText(_translate("Dialog", "Vulnerability:"))
        item = self.vmnInfoLIST.item(4)
        item.setText(_translate("Dialog", "Collector:"))
        self.vmnInfoLIST.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Dialog", "IP Adress"))
        self.label_3.setText(_translate("Dialog", "Port"))
        self.label_5.setText(_translate("Dialog", "Collector"))
        self.collectorCOMBO.setItemText(0, _translate("Dialog", "ECELd"))
        self.networkTrafficCHECKBOX.setText(_translate("Dialog", "Network Traffic"))
        self.systemLogsCHECKBOX.setText(_translate("Dialog", "System Logs"))
        self.apiCHECKBOX.setText(_translate("Dialog", "API Calls"))
        self.label_6.setText(_translate("Dialog", "Start Condition"))
        self.label_7.setText(_translate("Dialog", "Stop Condition"))
        self.stopConditionCOMBO.setItemText(0, _translate("Dialog", "Duration/Condition met"))
        self.timeoutCHECKBOX.setText(_translate("Dialog", "Timeout"))
        self.label_8.setText(_translate("Dialog", "Seconds"))
        self.label_4.setText(_translate("Dialog", "Scenario"))
        self.saveSessionBUTTON.setText(_translate("Dialog", "Save Session"))
        self.testNetworkBUTTON.setText(_translate("Dialog", "Test Network "))
        self.backBUTTON.setText(_translate("Dialog", "Back"))
        self.runScenarioBUTTON.setText(_translate("Dialog", "Run Scenario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
